language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t travis .
  - docker tag travis rtestdocker/travis:latest

after_success:
  - docker push rtestdocker/travis
  - echo "operation successful"
